# This section is for cost multipliers
# If a material does not have a multiplier listed, the plugin will use 1
# Please use the material prefix, ex: "WOODEN" for wood
cost_multis:
  LEATHER: 1
  WOODEN: 2
  STONE: 3
  IRON: 4
  GOLD: 5
  DIAMOND: 5
  NETHERITE: 10

# This section of the config contains enchantment groups that are mutually exclusive
exclusive_groups:
  1:
    - smite
    - sharpness
    - bane_of_arthropods
  2:
    - fortune
    - silk_touch

# To add tools to the enchanting category, please add the tool type name
# found https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Please exclude material types. For example, pickaxe enchantments are under
# the "PICKAXE" category.
# Enchantment names are the same as the enchantment in game
# Please use sounds from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# set a sound to "none" to remove it
enchanting:
  title: '&5&L-={Enchanter}=-'
  sound: ENTITY_PLAYER_LEVELUP
  block: ENCHANTING_TABLE
  token_lore:
    - 'This token is used to enchant items!'
  next_page:
    icon: ARROW
    name: '&A&LNext Page'
    lore:
      - '&7Click this to view the next page'
  prev_page:
    icon: ARROW
    name: '&A&LPrevious Page'
    lore:
      - '&7Click this to view the previous page'
  PICKAXE:
    efficiency:
      icon: GOLDEN_PICKAXE
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    fortune:
      icon: GOLDEN_PICKAXE
      max_level: 3
      level_costs:
        1: 1
        2: 2
        3: 5
    silk_touch:
      icon: GOLDEN_PICKAXE
      max_level: 1
      level_costs:
        1: 1
    unbreaking:
      icon: ANVIL
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    mending:
      icon: EXPERIENCE_BOTTLE
      max_level: 1
      level_costs:
        1: 25
  SWORD:
    sharpness:
      icon: GOLDEN_SWORD
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    smite:
      icon: GOLDEN_SWORD
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    bane_of_arthropods:
      icon: GOLDEN_SWORD
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    unbreaking:
      icon: ANVIL
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    mending:
      icon: EXPERIENCE_BOTTLE
      max_level: 1
      level_costs:
        1: 25
    fire_aspect:
      icon: BLAZE_POWDER
      max_level: 1
      level_costs:
        1: 25

# Below you can customize the enchantment books
# In the lore section, you can use %cost% as a placeholder for the enchantment cost

ebook:
  name: '&5&lEnchanting Book'
  lore:
    - '&7Drop me on an item to enchant it!'
    - '&7Cost: %cost% levels'
  level_cost:
    unbreaking:
      valid:
        - 'PICKAXE'
        - 'SHOVEL'
        - 'SWORD'
      1: 5
      2: 10
      3: 20
    fortune:
      valid:
        - 'PICKAXE'
      1: 5
    silk_touch:
      valid:
        - 'PICKAXE'
      1: 15

# Below is the section for disenchanting
disenchanting:
  title: '&4&L-={Disenchanter}=-'
  safe_title: '&2&L-={Safe disenchant}=-'
  unsafe_title: '&4&L-={Unsafe disenchant}=-'
  sound: BLOCK_ANVIL_BREAK
  block: GRINDSTONE
  safe:
    icon: GRINDSTONE
    name: '&A&LSafely disenchant'
    lore:
      - '&7Click this to safely disenchant your item'
  unsafe:
    icon: TNT
    name: '&C&LRisky disenchant!'
    lore:
      - '&7Click this to take a risk!!'
      - '&7You may receive some enchantments back'
      - '&7but your item will be consumed!'
  safe_confirm:
    icon: RED_STAINED_GLASS_PANE
    name: '&4&LCONFIRM DISENCHANT'
    lore:
      - '&7Clicking this will SAFELY disenchant'
      - '&7the item in the slot to the left!'
  unsafe_confirm:
    icon: RED_STAINED_GLASS_PANE
    name: '&4&LCONFIRM DISENCHANT'
    lore:
      - '&7Clicking this will UNSAFELY disenchant'
      - '&7the item in the slot to the left!'
      - '&7The item will be consumed, but you'
      - '&7may receive enchantment books!'
  unsafe_odds:
    LEATHER: 20
    WOODEN: 20
    STONE: 20
    IRON: 40
    GOLD: 50
    DIAMOND: 75
    NETHERITE: 100

# Below is the section for repairing and renaming
# Title is the title of the inventory, name is the name of the item
repair_rename:
  title: '&6&LSelect an option'
  block: ANVIL
repair:
  title: '&6&L-={Repair}=-'
  icon: ANVIL
  name: '&6&LRepair'
  sound: BLOCK_ANVIL_USE
  lore:
    - '&7Click this to open the repair menu'
  cost:
    LEATHER: 5
    WOODEN: 5
    STONE: 10
    IRON: 15
    GOLD: 20
    DIAMOND: 30
    NETHERITE: 50
  confirm:
    icon: LIME_STAINED_GLASS_PANE
    name: '&2&LConfirm'
    lore:
      - '&7Click this to repair the item in'
      - '&7the slot to the left!'
      - '&7Cost: %cost% levels'
rename:
  title: '&6&L-={Rename}=-'
  icon: NAME_TAG
  name: '&6&LRename'
  sound: BLOCK_ANVIL_USE
  max_length: 40
  lore:
    - '&7Click this to open the renaming menu'
  cost: 10
  confirm:
    icon: LIME_STAINED_GLASS_PANE
    name: '&2&LConfirm'
    lore:
      - '&7Click this to rename the item in'
      - '&7the slot to the left!'
      - '&7Cost: %cost% levels'