# To add tools to the enchanting category, please add the tool type name
# found https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Please exclude material types. For example, pickaxe enchantments are under
# the "PICKAXE" category.
# Please use enchantments from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
enchanting:
  block: ENCHANTING_TABLE
  token_lore:
    - 'This token is used to enchant items!'
  PICKAXE:
    DIG_SPEED:
      icon: GOLDEN_PICKAXE
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    DURABILITY:
      icon: ANVIL
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25
    MENDING:
      icon: EXPERIENCE_BOTTLE
      max_level: 1
      level_costs:
        1: 25
  SWORD:
    DAMAGE_ALL:
      icon: GOLDEN_SWORD
      max_level: 5
      level_costs:
        1: 1
        2: 2
        3: 5
        4: 10
        5: 25

# This section is for cost multipliers
# If a material does not have a multiplier listed, the plugin will use 1
# Please use the material prefix, ex: "WOODEN" for wood
cost_multis:
  LEATHER: 1
  WOODEN: 2
  STONE: 3
  IRON: 4
  GOLD: 5
  DIAMOND: 5
  NETHERITE: 10